In [69]:
# Most straight-forward way to import a library in Python
import requests

# BeautifulSoup is a module inside the "bs4" library, we only import the BeautifulSoup module
from bs4 import BeautifulSoup

# Pandas and numpy are always helpful
import numpy as np
import pandas as pd
import tweepy

In [70]:
headers = {"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"}
ksl_raw = requests.get('https://classifieds.ksl.com/search/keyword/arcteryx/priceFrom/0/priceTo/1000/Private/Sale',headers=headers).text
ksl_soup = BeautifulSoup(ksl_raw,'html.parser')
URL = 'https://classifieds.ksl.com/search/keyword/arcteryx/priceFrom/0/priceTo/1000/Private/Sale'

In [71]:
raw_listings = ksl_soup.find_all('section',{'class':'listing-item featured'})

In [72]:
def ExtractListingInfoDF(raw_listings):
    Titles = []
    Prices = []
    Locations = []
    for i in raw_listings:
        Titles.append(i.find('img')['alt'])
        Prices.append(i.find('div',{'class':'item-info-price info-line'}).text)
        Locations.append(i.find('a',{'class':'item-address'}).text)
    return pd.DataFrame({'Titles':Titles, 'Prices':Prices, 'Locations':Locations})

In [73]:
New_Listings = ExtractListingInfoDF(raw_listings)

In [74]:
New_Listings.head(23)

,Titles,Prices,Locations
0,Womens Arcteryx XS Jacket,$20.00,"Lehi, UT"
1,Arcteryx Side Winder Size LARGE $500 OBO,$500.00,"Millcreek, UT"
2,Arcteryx Long Sleeve Button Size Small,$25.00,"Draper, UT"
3,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT"
4,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT"
5,"Arcteryx , Kuhl, North Face Clothes",$35.00,"Layton, UT"
6,"Arcteryx, Kuhl, North Face Clothes Will Deliver",$25.00,"Layton, UT"
7,New Arcteryx Patera Parka XL,$500.00,"Salt Lake City, UT"
8,Women's Arcteryx Backpack: Bora 75,$120.00,"Salt Lake City, UT"
9,Arcteryx Women's Gore-Tex Shell,$80.00,"Salt Lake City, UT"
10,ArcTeryx Alpha AR,$300.00,"Lehi, UT"
11,Arcteryx Venta MX Hoody Jacket; Size XL,$360.00,"Draper, UT"
12,"Arcteryx Sabre Pant Gore Tex, Men's Large Like...",$360.00,"Draper, UT"
13,Arcteryx gortex shell,$300.00,"Ogden, UT"
14,Women’s Arcteryx Pants Size 8,$185.00,"Brigham City, UT"
15,Arcteryx Gryson Shirt LS Men's Flannel Sz Small,$60.00,"Park City, UT"
16,Arcteryx Softshell Jacket,$60.00,"Salt Lake City, UT"
17,Arcteryx Atom Lt Size Large Womens,$120.00,"Millcreek, UT"
18,Arcteryx Acrux FL Womens 7.5 NEW,$80.00,"Nibley, UT"
19,Arcteryx Ski Pants,$299.00,"Salt Lake City, UT"
20,ARCTERYX,$60.00,"Ogden, UT"
21,"Arcteryx Beta AR Pants Men's (M, Black)",$325.00,"Nibley, UT"

In [75]:
History = pd.read_csv('History.csv').iloc[:,1:]

In [76]:
History.head(23)

,Titles,Prices,Locations
0,Womens Arcteryx XS Jacket,$20.00,"Lehi, UT"
1,Arcteryx Side Winder Size LARGE $500 OBO,$500.00,"Millcreek, UT"
2,Arcteryx Long Sleeve Button Size Small,$25.00,"Draper, UT"
3,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT"
4,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT"
5,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT"
6,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT"
7,"Arcteryx , Kuhl, North Face Clothes",$35.00,"Layton, UT"
8,"Arcteryx, Kuhl, North Face Clothes Will Deliver",$25.00,"Layton, UT"
9,New Arcteryx Patera Parka XL,$500.00,"Salt Lake City, UT"
10,Women's Arcteryx Backpack: Bora 75,$120.00,"Salt Lake City, UT"
11,Arcteryx Women's Gore-Tex Shell,$80.00,"Salt Lake City, UT"
12,ArcTeryx Alpha AR,$300.00,"Lehi, UT"
13,Arcteryx Venta MX Hoody Jacket; Size XL,$360.00,"Draper, UT"
14,"Arcteryx Sabre Pant Gore Tex, Men's Large Like...",$360.00,"Draper, UT"
15,Arcteryx gortex shell,$300.00,"Ogden, UT"
16,Women’s Arcteryx Pants Size 8,$185.00,"Brigham City, UT"
17,Arcteryx Gryson Shirt LS Men's Flannel Sz Small,$60.00,"Park City, UT"
18,Arcteryx Softshell Jacket,$60.00,"Salt Lake City, UT"
19,Arcteryx Atom Lt Size Large Womens,$120.00,"Millcreek, UT"
20,Arcteryx Acrux FL Womens 7.5 NEW,$80.00,"Nibley, UT"
21,Arcteryx Ski Pants,$299.00,"Salt Lake City, UT"
22,ARCTERYX,$60.00,"Ogden, UT"

In [77]:
merged = pd.merge(New_Listings, History, on=['Titles','Prices','Locations'], how='outer', indicator=True)

In [78]:
merged

,Titles,Prices,Locations,_merge
0,Womens Arcteryx XS Jacket,$20.00,"Lehi, UT",both
1,Arcteryx Side Winder Size LARGE $500 OBO,$500.00,"Millcreek, UT",both
2,Arcteryx Long Sleeve Button Size Small,$25.00,"Draper, UT",both
3,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT",both
4,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT",both
5,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT",both
6,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT",both
7,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT",both
8,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT",both
9,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT",both
10,Men’s Arc'teryx Sabre AR Pants Arcteryx,$280.00,"Salt Lake City, UT",both
11,"Arcteryx , Kuhl, North Face Clothes",$35.00,"Layton, UT",both
12,"Arcteryx, Kuhl, North Face Clothes Will Deliver",$25.00,"Layton, UT",both
13,New Arcteryx Patera Parka XL,$500.00,"Salt Lake City, UT",both
14,Women's Arcteryx Backpack: Bora 75,$120.00,"Salt Lake City, UT",both
15,Arcteryx Women's Gore-Tex Shell,$80.00,"Salt Lake City, UT",both
16,ArcTeryx Alpha AR,$300.00,"Lehi, UT",both
17,Arcteryx Venta MX Hoody Jacket; Size XL,$360.00,"Draper, UT",both
18,"Arcteryx Sabre Pant Gore Tex, Men's Large Like...",$360.00,"Draper, UT",both
19,Arcteryx gortex shell,$300.00,"Ogden, UT",both
20,Women’s Arcteryx Pants Size 8,$185.00,"Brigham City, UT",both
21,Arcteryx Gryson Shirt LS Men's Flannel Sz Small,$60.00,"Park City, UT",both
22,Arcteryx Softshell Jacket,$60.00,"Salt Lake City, UT",both
23,Arcteryx Atom Lt Size Large Womens,$120.00,"Millcreek, UT",both
24,Arcteryx Acrux FL Womens 7.5 NEW,$80.00,"Nibley, UT",both
25,Arcteryx Ski Pants,$299.00,"Salt Lake City, UT",both
26,ARCTERYX,$60.00,"Ogden, UT",both
27,"Arcteryx Beta AR Pants Men's (M, Black)",$325.00,"Nibley, UT",both

In [79]:
tweet = merged[merged['_merge'] == 'left_only'].iloc[:,:-1]

In [80]:
tweet

Empty DataFrame
Columns: [Titles, Prices, Locations]
Index: []

In [81]:
merged.iloc[:,:-1].to_csv('History.csv')

In [82]:
consumer_key = '2LlCS74i3TcPCB1f1rMj2LrXi'
consumer_secret = 'fLQw16Rx2VSmnWmlGX6wQEO20ODnFVdQ4J8qPWTVG9npVzjRDv' 
access_token = '1490836142714810370-byS7DykGYT6MVWWJQv3SnPqHisTiD6' 
access_token_secret = 'X5llf5ERCIaTSD8MY8kWapbecwoMwJq2YGQp5IbnyCrtx'

In [83]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret) 
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

In [84]:
def GenerateTweetText(df_tweets):
    tweets = []
    for index,lab,price,loc in df_tweets.itertuples():
        tweets.append(f'GEAR ALERT: {lab} for {price} in {loc}')
    return tweets

In [85]:
to_tweet = list(set(GenerateTweetText(tweet)))

In [87]:
for i in to_tweet:
    try:
        api.update_status(i)
    except:
        pass